blank_issues_enabled: false
contact_links:   
  - name: Storyblok Discord (no official support is provided via Discord)
    url: https://discord.gg/WmMYYQp
    about: You can also join our Storyblok Discord community.
    
  - name: Storyblok Help Center/Service Desk - official support channel
    url: https://storyblok.atlassian.net/servicedesk/customer/portals
    about: You can raise a request for the Storyblok Service Desk.

  - name: Feature Requests
    url: https://feedback.storyblok.com/b/feature-requests/
    about: Please review the existing FRs on the platform before posting a new one.
